/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LayerData = IDL.Record({
  'id' : IDL.Nat,
  'fabricJson' : IDL.Text,
  'name' : IDL.Text,
  'visible' : IDL.Bool,
});
export const CreateProjectInput = IDL.Record({
  'height' : IDL.Nat,
  'imageRefs' : IDL.Vec(IDL.Text),
  'canvasJson' : IDL.Text,
  'name' : IDL.Text,
  'layers' : IDL.Vec(LayerData),
  'width' : IDL.Nat,
});
export const ProjectId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ProjectSummary = IDL.Record({
  'id' : ProjectId,
  'height' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'width' : IDL.Nat,
});
export const Project = IDL.Record({
  'id' : ProjectId,
  'height' : IDL.Nat,
  'imageRefs' : IDL.Vec(IDL.Text),
  'owner' : IDL.Principal,
  'canvasJson' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'layers' : IDL.Vec(LayerData),
  'updatedAt' : Timestamp,
  'width' : IDL.Nat,
});
export const UpdateProjectInput = IDL.Record({
  'id' : ProjectId,
  'height' : IDL.Nat,
  'imageRefs' : IDL.Vec(IDL.Text),
  'canvasJson' : IDL.Text,
  'name' : IDL.Text,
  'layers' : IDL.Vec(LayerData),
  'width' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createProject' : IDL.Func([CreateProjectInput], [ProjectId], []),
  'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
  'listProjects' : IDL.Func([], [IDL.Vec(ProjectSummary)], ['query']),
  'loadProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
  'saveProject' : IDL.Func([UpdateProjectInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LayerData = IDL.Record({
    'id' : IDL.Nat,
    'fabricJson' : IDL.Text,
    'name' : IDL.Text,
    'visible' : IDL.Bool,
  });
  const CreateProjectInput = IDL.Record({
    'height' : IDL.Nat,
    'imageRefs' : IDL.Vec(IDL.Text),
    'canvasJson' : IDL.Text,
    'name' : IDL.Text,
    'layers' : IDL.Vec(LayerData),
    'width' : IDL.Nat,
  });
  const ProjectId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ProjectSummary = IDL.Record({
    'id' : ProjectId,
    'height' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'width' : IDL.Nat,
  });
  const Project = IDL.Record({
    'id' : ProjectId,
    'height' : IDL.Nat,
    'imageRefs' : IDL.Vec(IDL.Text),
    'owner' : IDL.Principal,
    'canvasJson' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'layers' : IDL.Vec(LayerData),
    'updatedAt' : Timestamp,
    'width' : IDL.Nat,
  });
  const UpdateProjectInput = IDL.Record({
    'id' : ProjectId,
    'height' : IDL.Nat,
    'imageRefs' : IDL.Vec(IDL.Text),
    'canvasJson' : IDL.Text,
    'name' : IDL.Text,
    'layers' : IDL.Vec(LayerData),
    'width' : IDL.Nat,
  });
  
  return IDL.Service({
    'createProject' : IDL.Func([CreateProjectInput], [ProjectId], []),
    'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
    'listProjects' : IDL.Func([], [IDL.Vec(ProjectSummary)], ['query']),
    'loadProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
    'saveProject' : IDL.Func([UpdateProjectInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };