/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateProjectInput {
  'height' : bigint,
  'imageRefs' : Array<string>,
  'canvasJson' : string,
  'name' : string,
  'layers' : Array<LayerData>,
  'width' : bigint,
}
export interface LayerData {
  'id' : bigint,
  'fabricJson' : string,
  'name' : string,
  'visible' : boolean,
}
export interface Project {
  'id' : ProjectId,
  'height' : bigint,
  'imageRefs' : Array<string>,
  'owner' : Principal,
  'canvasJson' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'layers' : Array<LayerData>,
  'updatedAt' : Timestamp,
  'width' : bigint,
}
export type ProjectId = bigint;
export interface ProjectSummary {
  'id' : ProjectId,
  'height' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'width' : bigint,
}
export type Timestamp = bigint;
export interface UpdateProjectInput {
  'id' : ProjectId,
  'height' : bigint,
  'imageRefs' : Array<string>,
  'canvasJson' : string,
  'name' : string,
  'layers' : Array<LayerData>,
  'width' : bigint,
}
export interface _SERVICE {
  'createProject' : ActorMethod<[CreateProjectInput], ProjectId>,
  'deleteProject' : ActorMethod<[ProjectId], boolean>,
  'listProjects' : ActorMethod<[], Array<ProjectSummary>>,
  'loadProject' : ActorMethod<[ProjectId], [] | [Project]>,
  'saveProject' : ActorMethod<[UpdateProjectInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];